heading-increment: true
heading-style:
  style: atx
ul-style:
  style: dash
list-indent: true
ul-indent:
  indent: 2
  start_indented: false
no-trailing-spaces:
  br_spaces: 2
  list_item_empty_lines: false
  strict: true
no-hard-tabs:
  code_blocks: true
  spaces_per_tab: 2
no-reversed-links: true
no-multiple-blanks:
  maximum: 1
line-length:
  line_length: 80
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false
commands-show-output: false
no-missing-space-atx: true
no-multiple-space-atx: true
blanks-around-headings:
  lines_above: 1
  lines_below: 1
heading-start-left: true
no-duplicate-heading:
  siblings_only: true
single-h1:
  level: 1
  front_matter_title: ^\\s*title\\s*[:]
no-trailing-punctuation: false
no-multiple-space-blockquote: true
no-blanks-blockquote: false
ol-prefix:
  style: one
list-marker-space:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1
blanks-around-fences:
  list_items: false
no-inline-html: true
no-bare-urls: true
hr-style:
  style: ---
no-emphasis-as-heading: true
no-space-in-emphasis: true
no-space-in-code: true
no-space-in-links: true
fenced-code-language: false
first-line-heading: false
no-empty-links: true
proper-names:
  code_blocks: false
  names:
  - Bash
  - Zsh
  - Python
  - Emacs Lisp
  - Jq
  - Sed
  - Awk
  - Emacs
  - Sublime Text
  - Git
  - GitHub
  - C#
  - PascalABC.NET
  - Krita
  - Google Slides
no-alt-text: true
code-block-style:
  style: fenced
single-trailing-newline: true
code-fence-style:
  style: backtick
