name: Check Markdown files
on:
  workflow_call:
    inputs:
      config-name:
        description: Config name to check without extension
        type: string
        required: false
        default: base

jobs:
  check:
    if: inputs.config-name == 'base' || inputs.config-name == 'package'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install --global markdownlint-cli
    - run: |
        shopt -s globstar nullglob
        name="$(mktemp)"
        endpoint='https://api.github.com'
        repository='EmilySeville7cfg/personal-automation-helpers'
        file='linters/markdownlint/${{ inputs.config-name }}.yaml'
        curl --header 'accept: application/vnd.github.v3+json' \
          --user "EmilySeville7cfg:${{ secrets.REPO_ACCESS_TOKEN }}" \
          "$endpoint/repos/$repository/contents/$file" 2> /dev/null |
          jq --raw-output '.content' |
          base64 --decode > "$name" ||
          exit "Can't obtain `markdownlint` config."
        echo "Config selected:"
        cat "$name"

        lint_command="markdownlint --config \"$name\" **/*.md **/*.markdown"
        echo Executing linting command: $lint_command
        $lint_command
