name: Check YAML files
on:
  workflow_call: null

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - run: |
        shopt -s globstar nullglob
        declare name="$(mktemp)"
        declare endpoint='https://api.github.com'
        declare repository='EmilySeville7cfg/personal-automation-helpers'
        declare file='linters/yamllint/base.yaml'
        curl --header 'accept: application/vnd.github.v3+json' \
          --user "EmilySeville7cfg:${{ secrets.REPO_ACCESS_TOKEN }}" \
          "$endpoint/repos/$repository/contents/$file" 2> /dev/null |
          jq --raw-output '.content' |
          base64 --decode > "$name" || exit "Can't obtain `yamllint` config."
        echo "Config selected:"
        cat "$name"
        yamllint --config-file "$name" **/*.{yaml,yml}
