name: CI
on:
  pull_request:
    branches:
    - main

jobs:
  check-yaml:
    uses: ./.github/workflows/check-yaml.yaml
  check-markdown:
    uses: ./.github/workflows/check-markdown.yaml
    with:
      config-name: base
